<?php

namespace Amazon\API\Products;

class ListMatchingProducts extends Products
{

    protected static $requestQuota = 20;
    protected static $restoreRate = 1;
    protected static $restoreRateTime = 5;
    protected static $restoreRateTimePeriod = "second";
    protected static $hourlyRequestQuota = 720;
    protected static $method = "POST";
    private static $curlParameters = [];
    private static $apiUrl = "http://docs.developer.amazonservices.com/en_US/products/Products_ListMatchingProducts.html";
    protected static $requiredParameters = [];
    protected static $allowedParameters = [];
    protected static $parameters = [
        "MarketplaceId" => [
            "required"
        ],
        "Query" => [
            "required"
        ],
        "QueryContextId" => [
            "validWith" => [
                "CA" => [
                    "All",
                    "Books",
                    "Classical",
                    "DVD",
                    "Electronics",
                    "ForeignBooks",
                    "Kitchen",
                    "Music",
                    "Software",
                    "VHS",
                    "Video",
                    "VideoGames"
                ],
                "CN" => [
                    "All",
                    "Apparel",
                    "Appliances",
                    "Automotive",
                    "Baby",
                    "Beauty",
                    "Books",
                    "Electronics",
                    "Grocery",
                    "HealthPersonalCare",
                    "Home",
                    "HomeImprovement",
                    "Jewelry",
                    "Misc",
                    "Music",
                    "OfficeProducts",
                    "Photo",
                    "Shoes",
                    "Software",
                    "SportingGoods",
                    "Toys",
                    "Video",
                    "VideoGames",
                    "Watches"
                ],
                "DE" => [
                    "All",
                    "Apparel",
                    "Automotive",
                    "Baby",
                    "Beauty",
                    "Books",
                    "Classical",
                    "DVD",
                    "Electronics",
                    "ForeignBooks",
                    "Grocery",
                    "HealthPersonalCare",
                    "HomeGarden",
                    "Jewelry",
                    "KindleStore",
                    "Kitchen",
                    "Lighting",
                    "Magazines",
                    "MP3Downloads",
                    "Music",
                    "MusicalInstruments",
                    "MusicTracks",
                    "OfficeProducts",
                    "OutdoorLiving",
                    "Outlet",
                    "PCHardware",
                    "Photo",
                    "Software",
                    "SportingGoods",
                    "Tools",
                    "Toys",
                    "VHS",
                    "Video",
                    "VideoGames",
                    "Watches"
                ],
                "ES" => [
                    "All",
                    "Books",
                    "DVD",
                    "Electronics",
                    "ForeignBooks",
                    "Kitchen",
                    "Music",
                    "Software",
                    "Toys",
                    "VideoGames",
                    "Watches"
                ],
                "FR" => [
                    "All",
                    "Apparel",
                    "Baby",
                    "Beauty",
                    "Books",
                    "Classical",
                    "DVD",
                    "Electronics",
                    "ForeignBooks",
                    "HealthPersonalCare",
                    "Jewelry",
                    "Kitchen",
                    "Lighting",
                    "MP3Downloads",
                    "Music",
                    "MusicalInstruments",
                    "MusicTracks",
                    "OfficeProducts",
                    "Shoes",
                    "Software",
                    "VHS",
                    "Video",
                    "VideoGames",
                    "Watches"
                ],
                "IT" => [
                    "All",
                    "Books",
                    "DVD",
                    "Electronics",
                    "ForeignBooks",
                    "Garden",
                    "Kitchen",
                    "Music",
                    "Shoes",
                    "Software",
                    "Toys",
                    "VideoGames",
                    "Watches"
                ],
                "MX" => [
                    "All",
                    "Baby",
                    "Books",
                    "DVD",
                    "Electronics",
                    "HealthPersonalCare",
                    "HomeImprovement",
                    "Kitchen",
                    "KindleStore",
                    "Music",
                    "OfficeProducts",
                    "PetSupplies",
                    "Software",
                    "SportingGoods",
                    "Toys",
                    "VideoGames",
                    "Watches"
                ],
                "JP" => [
                    "All",
                    "Apparel",
                    "Automotive",
                    "Baby",
                    "Beauty",
                    "Books",
                    "Classical",
                    "DVD",
                    "Electronics",
                    "ForeignBooks",
                    "Grocery",
                    "HealthPersonalCare",
                    "Hobbies",
                    "HomeImprovement",
                    "Jewelry",
                    "Kitchen",
                    "MP3Downloads",
                    "Music",
                    "MusicalInstruments",
                    "MusicTracks",
                    "OfficeProducts",
                    "Shoes",
                    "Software",
                    "SportingGoods",
                    "Toys",
                    "VHS",
                    "Video",
                    "VideoGames",
                    "Watches"
                ],
                "UK" => [
                    "All",
                    "Apparel",
                    "Automotive",
                    "Baby",
                    "Beauty",
                    "Books",
                    "Classical",
                    "DVD",
                    "Electronics",
                    "Grocery",
                    "HealthPersonalCare",
                    "HomeGarden",
                    "Jewelry",
                    "Kitchen",
                    "Lighting",
                    "MP3Downloads",
                    "Music",
                    "MusicalInstruments",
                    "MusicTracks",
                    "OfficeProducts",
                    "OutdoorLiving",
                    "Outlet",
                    "Shoes",
                    "Software",
                    "SoftwareVideoGames",
                    "Toys",
                    "VHS",
                    "Video",
                    "VideoGames",
                    "Watches"
                ],
                "US" => [
                    "All",
                    "Apparel",
                    "Appliances",
                    "ArtsAndCrafts",
                    "Automotive",
                    "Baby",
                    "Beauty",
                    "Books",
                    "Classical",
                    "DigitalMusic",
                    "DVD",
                    "Electronics",
                    "Grocery",
                    "HealthPersonalCare",
                    "HomeGarden",
                    "Industrial",
                    "Jewelry",
                    "KindleStore",
                    "Kitchen",
                    "Magazines",
                    "Miscellaneous",
                    "MobileApps",
                    "MP3Downloads",
                    "Music",
                    "MusicalInstruments",
                    "OfficeProducts",
                    "PCHardware",
                    "PetSupplies",
                    "Photo",
                    "Shoes",
                    "Software",
                    "SportingGoods",
                    "Tools",
                    "Toys",
                    "UnboxVideo",
                    "VHS",
                    "Video",
                    "VideoGames",
                    "Watches",
                    "Wireless",
                    "WirelessAccessories"
                ]
            ]
        ]
    ];

}